restaurant_choices = {
  'a': 'The Roost',
  'b': 'Jefes Tacos & Tequila',
  'c': 'Georgia Boys BBQ',
  'd': 'Pumphouse Brewery',
  'e': 'Martinis Bistro',
  'f': 'Cheba Hut',
  'g': 'TGI Fridays',
  'h': 'Sumo Japanese Restaurant',
  'i': 'Smoking Bowls',
  'j': 'Goodfellas Diner',
  'k': 'Las Palmeras',
  'l': 'Tequilas',
  'm': 'Tangerine',
  'n': 'Taco Palace',
  'o': 'Panera Bread',
  'p': 'Taco Bell',
  'q': 'Collision Brewing',
  'r': 'Panda Express',
  's': 'Chipotle',
  't': 'Texas Roadhouse',
  'u': 'Oscar Blues',
  'v': 'Le Peep',
  'w': '5 Guys burgers',
  'x': 'Bad Daddys',
  'y': 'Parrys Pizza',
  'z': 'Buffalo Wild Wings'
}