restaurant_type = {
  'The Roost': set(['Breakfast', 'Lunch', 'Dinner', 'American']),
  'Jefes Tacos & Tequila': set(['Lunch', 'Dinner', 'Mexican']),
  'Georgia Boys BBQ': set(['Lunch', 'Dinner', 'Mexican']),
  'Pumphouse Brewery': set(['Lunch', 'Dinner', 'American', 'Brewery']),
  'Martinis Bistro': set(['Breakfast', 'Lunch', 'Dinner', 'American']),
  'Cheba Hut': set(['Lunch', 'Dinner', 'American', 'Sandwiches']),
  'TGI Fridays': set(['Lunch', 'Dinner', 'American']),
  'Sumo Japanese Restaurant': set(['Lunch', 'Dinner', 'Asian']),
  'Smoking Bowls': set(['Lunch', 'Dinner', 'American']),
  'Goodfellas Diner': set(['Breakfast', 'Lunch', 'Dinner', 'American']),
  'Las Palmeras': set(['Breakfast', 'Lunch', 'Dinner', 'Mexican']),
  'Tequilas': set(['Breakfast', 'Lunch', 'Dinner', 'Mexican']),
  'Tangerine': set(['Lunch', 'Dinner', 'American']),
  'Taco Palace': set(['Breakfast', 'Lunch', 'Dinner', 'Mexican']),
  'Panera Bread': set(['Breakfast', 'Lunch', 'Dinner', 'American']),
  'Taco Bell': set(['Breakfast', 'Lunch', 'Dinner', 'Mexican']),
  'Collision Brewing': set(['Lunch', 'Dinner', 'American', 'Brewery']),
  'Panda Express': set(['Lunch', 'Dinner', 'Asian']),
  'Chipotle': set(['Lunch', 'Dinner', 'Mexican']),
  'Texas Roadhouse': set(['Lunch', 'Dinner', 'American']),
  'Oscar Blues': set(['Lunch', 'Dinner', 'American', 'Brewery']),
  'Le Peep': set(['Breakfast', 'Lunch', 'American']),
  '5 Guys burgers': set(['Lunch', 'Dinner', 'American']),
  'Bad Daddys': set(['Lunch', 'Dinner', 'American']),
  'Parrys Pizza': set(['Lunch', 'Dinner', 'Italian']),
  'Buffalo Wild Wings': set(['Lunch', 'Dinner', 'American'])
}